// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: base_type.proto

package go_jeans

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseType_PB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B    bool    `protobuf:"varint,1,opt,name=b,proto3" json:"b,omitempty"`
	I    int32   `protobuf:"varint,2,opt,name=i,proto3" json:"i,omitempty"`
	I8   int32   `protobuf:"varint,3,opt,name=i8,proto3" json:"i8,omitempty"`
	I16  int32   `protobuf:"varint,4,opt,name=i16,proto3" json:"i16,omitempty"`
	I32  int32   `protobuf:"varint,5,opt,name=i32,proto3" json:"i32,omitempty"`
	I64  int64   `protobuf:"varint,6,opt,name=i64,proto3" json:"i64,omitempty"`
	Ui   uint32  `protobuf:"varint,7,opt,name=ui,proto3" json:"ui,omitempty"`
	Ui8  uint32  `protobuf:"varint,8,opt,name=ui8,proto3" json:"ui8,omitempty"`
	Ui16 uint32  `protobuf:"varint,9,opt,name=ui16,proto3" json:"ui16,omitempty"`
	Ui32 uint32  `protobuf:"varint,10,opt,name=ui32,proto3" json:"ui32,omitempty"`
	Ui64 uint64  `protobuf:"varint,11,opt,name=ui64,proto3" json:"ui64,omitempty"`
	Bs   []byte  `protobuf:"bytes,12,opt,name=bs,proto3" json:"bs,omitempty"`
	F32  float32 `protobuf:"fixed32,13,opt,name=f32,proto3" json:"f32,omitempty"`
	F64  float64 `protobuf:"fixed64,14,opt,name=f64,proto3" json:"f64,omitempty"`
	S    string  `protobuf:"bytes,15,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *BaseType_PB) Reset() {
	*x = BaseType_PB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseType_PB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseType_PB) ProtoMessage() {}

func (x *BaseType_PB) ProtoReflect() protoreflect.Message {
	mi := &file_base_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseType_PB.ProtoReflect.Descriptor instead.
func (*BaseType_PB) Descriptor() ([]byte, []int) {
	return file_base_type_proto_rawDescGZIP(), []int{0}
}

func (x *BaseType_PB) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *BaseType_PB) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *BaseType_PB) GetI8() int32 {
	if x != nil {
		return x.I8
	}
	return 0
}

func (x *BaseType_PB) GetI16() int32 {
	if x != nil {
		return x.I16
	}
	return 0
}

func (x *BaseType_PB) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *BaseType_PB) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *BaseType_PB) GetUi() uint32 {
	if x != nil {
		return x.Ui
	}
	return 0
}

func (x *BaseType_PB) GetUi8() uint32 {
	if x != nil {
		return x.Ui8
	}
	return 0
}

func (x *BaseType_PB) GetUi16() uint32 {
	if x != nil {
		return x.Ui16
	}
	return 0
}

func (x *BaseType_PB) GetUi32() uint32 {
	if x != nil {
		return x.Ui32
	}
	return 0
}

func (x *BaseType_PB) GetUi64() uint64 {
	if x != nil {
		return x.Ui64
	}
	return 0
}

func (x *BaseType_PB) GetBs() []byte {
	if x != nil {
		return x.Bs
	}
	return nil
}

func (x *BaseType_PB) GetF32() float32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *BaseType_PB) GetF64() float64 {
	if x != nil {
		return x.F64
	}
	return 0
}

func (x *BaseType_PB) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_base_type_proto protoreflect.FileDescriptor

var file_base_type_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x50,
	0x42, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x62, 0x12,
	0x0c, 0x0a, 0x01, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x38, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x38, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x31, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x69, 0x31, 0x36, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x69, 0x33,
	0x32, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x69, 0x36, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x75, 0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x75, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x38, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x75, 0x69, 0x38, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x31, 0x36, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x31, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x33,
	0x32, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x33, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x69, 0x36, 0x34, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x69, 0x36,
	0x34, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x62,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x33, 0x32, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x66, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x36, 0x34, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x66, 0x36, 0x34, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x67, 0x6f, 0x5f, 0x6a, 0x65, 0x61,
	0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_type_proto_rawDescOnce sync.Once
	file_base_type_proto_rawDescData = file_base_type_proto_rawDesc
)

func file_base_type_proto_rawDescGZIP() []byte {
	file_base_type_proto_rawDescOnce.Do(func() {
		file_base_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_type_proto_rawDescData)
	})
	return file_base_type_proto_rawDescData
}

var file_base_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_type_proto_goTypes = []interface{}{
	(*BaseType_PB)(nil), // 0: BaseType_PB
}
var file_base_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_type_proto_init() }
func file_base_type_proto_init() {
	if File_base_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseType_PB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_type_proto_goTypes,
		DependencyIndexes: file_base_type_proto_depIdxs,
		MessageInfos:      file_base_type_proto_msgTypes,
	}.Build()
	File_base_type_proto = out.File
	file_base_type_proto_rawDesc = nil
	file_base_type_proto_goTypes = nil
	file_base_type_proto_depIdxs = nil
}
